{{- if .Values.clickhouse.deploy -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse.fullname" . }}-clickhouse
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
type: Opaque
data:
  admin-password: {{ .Values.clickhouse.auth.password | b64enc | quote }}
{{- end }}
